/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAnalyticsRouteImport } from './routes/admin/analytics'
import { Route as AdminAuditRouteImport } from './routes/admin/audit'
import { Route as AdminHealthRouteImport } from './routes/admin/health'
import { Route as AdminRulesRouteImport } from './routes/admin/rules'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminSourcesRouteImport } from './routes/admin/sources'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminVesselsRouteImport } from './routes/admin/vessels'
import { Route as AdminZonesRouteImport } from './routes/admin/zones'
import { Route as CommandIndexRouteImport } from './routes/command/index'
import { Route as CommandAlertsRouteImport } from './routes/command/alerts'
import { Route as CommandAnalyticsRouteImport } from './routes/command/analytics'
import { Route as CommandAssignmentsRouteImport } from './routes/command/assignments'
import { Route as CommandEvidenceRouteImport } from './routes/command/evidence'
import { Route as CommandIncidentsRouteImport } from './routes/command/incidents'
import { Route as CommandMapRouteImport } from './routes/command/map'
import { Route as CommandThreatsRouteImport } from './routes/command/threats'
import { Route as CommandTwinRouteImport } from './routes/command/twin'
import { Route as CommandVesselsRouteImport } from './routes/command/vessels'
import { Route as FieldIndexRouteImport } from './routes/field/index'
import { Route as FieldActiveRouteImport } from './routes/field/active'
import { Route as FieldAssignmentsRouteImport } from './routes/field/assignments'
import { Route as FieldEvidenceRouteImport } from './routes/field/evidence'
import { Route as FieldMissionRouteImport } from './routes/field/mission'
import { Route as FieldReportsRouteImport } from './routes/field/reports'
import { Route as FieldUpdatesRouteImport } from './routes/field/updates'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminHealthRoute = AdminHealthRouteImport.update({
  id: '/admin/health',
  path: '/admin/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRulesRoute = AdminRulesRouteImport.update({
  id: '/admin/rules',
  path: '/admin/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSourcesRoute = AdminSourcesRouteImport.update({
  id: '/admin/sources',
  path: '/admin/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVesselsRoute = AdminVesselsRouteImport.update({
  id: '/admin/vessels',
  path: '/admin/vessels',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminZonesRoute = AdminZonesRouteImport.update({
  id: '/admin/zones',
  path: '/admin/zones',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandIndexRoute = CommandIndexRouteImport.update({
  id: '/command/',
  path: '/command/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandAlertsRoute = CommandAlertsRouteImport.update({
  id: '/command/alerts',
  path: '/command/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandAnalyticsRoute = CommandAnalyticsRouteImport.update({
  id: '/command/analytics',
  path: '/command/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandAssignmentsRoute = CommandAssignmentsRouteImport.update({
  id: '/command/assignments',
  path: '/command/assignments',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandEvidenceRoute = CommandEvidenceRouteImport.update({
  id: '/command/evidence',
  path: '/command/evidence',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandIncidentsRoute = CommandIncidentsRouteImport.update({
  id: '/command/incidents',
  path: '/command/incidents',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandMapRoute = CommandMapRouteImport.update({
  id: '/command/map',
  path: '/command/map',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandThreatsRoute = CommandThreatsRouteImport.update({
  id: '/command/threats',
  path: '/command/threats',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandTwinRoute = CommandTwinRouteImport.update({
  id: '/command/twin',
  path: '/command/twin',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandVesselsRoute = CommandVesselsRouteImport.update({
  id: '/command/vessels',
  path: '/command/vessels',
  getParentRoute: () => rootRouteImport,
} as any)
const FieldIndexRoute = FieldIndexRouteImport.update({
  id: '/field/',
  path: '/field/',
  getParentRoute: () => rootRouteImport,
} as any)
const FieldActiveRoute = FieldActiveRouteImport.update({
  id: '/field/active',
  path: '/field/active',
  getParentRoute: () => rootRouteImport,
} as any)
const FieldAssignmentsRoute = FieldAssignmentsRouteImport.update({
  id: '/field/assignments',
  path: '/field/assignments',
  getParentRoute: () => rootRouteImport,
} as any)
const FieldEvidenceRoute = FieldEvidenceRouteImport.update({
  id: '/field/evidence',
  path: '/field/evidence',
  getParentRoute: () => rootRouteImport,
} as any)
const FieldMissionRoute = FieldMissionRouteImport.update({
  id: '/field/mission',
  path: '/field/mission',
  getParentRoute: () => rootRouteImport,
} as any)
const FieldReportsRoute = FieldReportsRouteImport.update({
  id: '/field/reports',
  path: '/field/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const FieldUpdatesRoute = FieldUpdatesRouteImport.update({
  id: '/field/updates',
  path: '/field/updates',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/health': typeof AdminHealthRoute
  '/admin/rules': typeof AdminRulesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sources': typeof AdminSourcesRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/vessels': typeof AdminVesselsRoute
  '/admin/zones': typeof AdminZonesRoute
  '/command/alerts': typeof CommandAlertsRoute
  '/command/analytics': typeof CommandAnalyticsRoute
  '/command/assignments': typeof CommandAssignmentsRoute
  '/command/evidence': typeof CommandEvidenceRoute
  '/command/incidents': typeof CommandIncidentsRoute
  '/command/map': typeof CommandMapRoute
  '/command/threats': typeof CommandThreatsRoute
  '/command/twin': typeof CommandTwinRoute
  '/command/vessels': typeof CommandVesselsRoute
  '/field/active': typeof FieldActiveRoute
  '/field/assignments': typeof FieldAssignmentsRoute
  '/field/evidence': typeof FieldEvidenceRoute
  '/field/mission': typeof FieldMissionRoute
  '/field/reports': typeof FieldReportsRoute
  '/field/updates': typeof FieldUpdatesRoute
  '/admin/': typeof AdminIndexRoute
  '/command/': typeof CommandIndexRoute
  '/field/': typeof FieldIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/health': typeof AdminHealthRoute
  '/admin/rules': typeof AdminRulesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sources': typeof AdminSourcesRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/vessels': typeof AdminVesselsRoute
  '/admin/zones': typeof AdminZonesRoute
  '/command/alerts': typeof CommandAlertsRoute
  '/command/analytics': typeof CommandAnalyticsRoute
  '/command/assignments': typeof CommandAssignmentsRoute
  '/command/evidence': typeof CommandEvidenceRoute
  '/command/incidents': typeof CommandIncidentsRoute
  '/command/map': typeof CommandMapRoute
  '/command/threats': typeof CommandThreatsRoute
  '/command/twin': typeof CommandTwinRoute
  '/command/vessels': typeof CommandVesselsRoute
  '/field/active': typeof FieldActiveRoute
  '/field/assignments': typeof FieldAssignmentsRoute
  '/field/evidence': typeof FieldEvidenceRoute
  '/field/mission': typeof FieldMissionRoute
  '/field/reports': typeof FieldReportsRoute
  '/field/updates': typeof FieldUpdatesRoute
  '/admin': typeof AdminIndexRoute
  '/command': typeof CommandIndexRoute
  '/field': typeof FieldIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/health': typeof AdminHealthRoute
  '/admin/rules': typeof AdminRulesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sources': typeof AdminSourcesRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/vessels': typeof AdminVesselsRoute
  '/admin/zones': typeof AdminZonesRoute
  '/command/alerts': typeof CommandAlertsRoute
  '/command/analytics': typeof CommandAnalyticsRoute
  '/command/assignments': typeof CommandAssignmentsRoute
  '/command/evidence': typeof CommandEvidenceRoute
  '/command/incidents': typeof CommandIncidentsRoute
  '/command/map': typeof CommandMapRoute
  '/command/threats': typeof CommandThreatsRoute
  '/command/twin': typeof CommandTwinRoute
  '/command/vessels': typeof CommandVesselsRoute
  '/field/active': typeof FieldActiveRoute
  '/field/assignments': typeof FieldAssignmentsRoute
  '/field/evidence': typeof FieldEvidenceRoute
  '/field/mission': typeof FieldMissionRoute
  '/field/reports': typeof FieldReportsRoute
  '/field/updates': typeof FieldUpdatesRoute
  '/admin/': typeof AdminIndexRoute
  '/command/': typeof CommandIndexRoute
  '/field/': typeof FieldIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/notifications'
    | '/profile'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/health'
    | '/admin/rules'
    | '/admin/settings'
    | '/admin/sources'
    | '/admin/users'
    | '/admin/vessels'
    | '/admin/zones'
    | '/command/alerts'
    | '/command/analytics'
    | '/command/assignments'
    | '/command/evidence'
    | '/command/incidents'
    | '/command/map'
    | '/command/threats'
    | '/command/twin'
    | '/command/vessels'
    | '/field/active'
    | '/field/assignments'
    | '/field/evidence'
    | '/field/mission'
    | '/field/reports'
    | '/field/updates'
    | '/admin/'
    | '/command/'
    | '/field/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/notifications'
    | '/profile'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/health'
    | '/admin/rules'
    | '/admin/settings'
    | '/admin/sources'
    | '/admin/users'
    | '/admin/vessels'
    | '/admin/zones'
    | '/command/alerts'
    | '/command/analytics'
    | '/command/assignments'
    | '/command/evidence'
    | '/command/incidents'
    | '/command/map'
    | '/command/threats'
    | '/command/twin'
    | '/command/vessels'
    | '/field/active'
    | '/field/assignments'
    | '/field/evidence'
    | '/field/mission'
    | '/field/reports'
    | '/field/updates'
    | '/admin'
    | '/command'
    | '/field'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/notifications'
    | '/profile'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/health'
    | '/admin/rules'
    | '/admin/settings'
    | '/admin/sources'
    | '/admin/users'
    | '/admin/vessels'
    | '/admin/zones'
    | '/command/alerts'
    | '/command/analytics'
    | '/command/assignments'
    | '/command/evidence'
    | '/command/incidents'
    | '/command/map'
    | '/command/threats'
    | '/command/twin'
    | '/command/vessels'
    | '/field/active'
    | '/field/assignments'
    | '/field/evidence'
    | '/field/mission'
    | '/field/reports'
    | '/field/updates'
    | '/admin/'
    | '/command/'
    | '/field/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  ProfileRoute: typeof ProfileRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminHealthRoute: typeof AdminHealthRoute
  AdminRulesRoute: typeof AdminRulesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSourcesRoute: typeof AdminSourcesRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVesselsRoute: typeof AdminVesselsRoute
  AdminZonesRoute: typeof AdminZonesRoute
  CommandAlertsRoute: typeof CommandAlertsRoute
  CommandAnalyticsRoute: typeof CommandAnalyticsRoute
  CommandAssignmentsRoute: typeof CommandAssignmentsRoute
  CommandEvidenceRoute: typeof CommandEvidenceRoute
  CommandIncidentsRoute: typeof CommandIncidentsRoute
  CommandMapRoute: typeof CommandMapRoute
  CommandThreatsRoute: typeof CommandThreatsRoute
  CommandTwinRoute: typeof CommandTwinRoute
  CommandVesselsRoute: typeof CommandVesselsRoute
  FieldActiveRoute: typeof FieldActiveRoute
  FieldAssignmentsRoute: typeof FieldAssignmentsRoute
  FieldEvidenceRoute: typeof FieldEvidenceRoute
  FieldMissionRoute: typeof FieldMissionRoute
  FieldReportsRoute: typeof FieldReportsRoute
  FieldUpdatesRoute: typeof FieldUpdatesRoute
  AdminIndexRoute: typeof AdminIndexRoute
  CommandIndexRoute: typeof CommandIndexRoute
  FieldIndexRoute: typeof FieldIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/health': {
      id: '/admin/health'
      path: '/admin/health'
      fullPath: '/admin/health'
      preLoaderRoute: typeof AdminHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/rules': {
      id: '/admin/rules'
      path: '/admin/rules'
      fullPath: '/admin/rules'
      preLoaderRoute: typeof AdminRulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/sources': {
      id: '/admin/sources'
      path: '/admin/sources'
      fullPath: '/admin/sources'
      preLoaderRoute: typeof AdminSourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/vessels': {
      id: '/admin/vessels'
      path: '/admin/vessels'
      fullPath: '/admin/vessels'
      preLoaderRoute: typeof AdminVesselsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/zones': {
      id: '/admin/zones'
      path: '/admin/zones'
      fullPath: '/admin/zones'
      preLoaderRoute: typeof AdminZonesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/command/': {
      id: '/command/'
      path: '/command'
      fullPath: '/command/'
      preLoaderRoute: typeof CommandIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/command/alerts': {
      id: '/command/alerts'
      path: '/command/alerts'
      fullPath: '/command/alerts'
      preLoaderRoute: typeof CommandAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/command/analytics': {
      id: '/command/analytics'
      path: '/command/analytics'
      fullPath: '/command/analytics'
      preLoaderRoute: typeof CommandAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/command/assignments': {
      id: '/command/assignments'
      path: '/command/assignments'
      fullPath: '/command/assignments'
      preLoaderRoute: typeof CommandAssignmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/command/evidence': {
      id: '/command/evidence'
      path: '/command/evidence'
      fullPath: '/command/evidence'
      preLoaderRoute: typeof CommandEvidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/command/incidents': {
      id: '/command/incidents'
      path: '/command/incidents'
      fullPath: '/command/incidents'
      preLoaderRoute: typeof CommandIncidentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/command/map': {
      id: '/command/map'
      path: '/command/map'
      fullPath: '/command/map'
      preLoaderRoute: typeof CommandMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/command/threats': {
      id: '/command/threats'
      path: '/command/threats'
      fullPath: '/command/threats'
      preLoaderRoute: typeof CommandThreatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/command/twin': {
      id: '/command/twin'
      path: '/command/twin'
      fullPath: '/command/twin'
      preLoaderRoute: typeof CommandTwinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/command/vessels': {
      id: '/command/vessels'
      path: '/command/vessels'
      fullPath: '/command/vessels'
      preLoaderRoute: typeof CommandVesselsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/field/': {
      id: '/field/'
      path: '/field'
      fullPath: '/field/'
      preLoaderRoute: typeof FieldIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/field/active': {
      id: '/field/active'
      path: '/field/active'
      fullPath: '/field/active'
      preLoaderRoute: typeof FieldActiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/field/assignments': {
      id: '/field/assignments'
      path: '/field/assignments'
      fullPath: '/field/assignments'
      preLoaderRoute: typeof FieldAssignmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/field/evidence': {
      id: '/field/evidence'
      path: '/field/evidence'
      fullPath: '/field/evidence'
      preLoaderRoute: typeof FieldEvidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/field/mission': {
      id: '/field/mission'
      path: '/field/mission'
      fullPath: '/field/mission'
      preLoaderRoute: typeof FieldMissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/field/reports': {
      id: '/field/reports'
      path: '/field/reports'
      fullPath: '/field/reports'
      preLoaderRoute: typeof FieldReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/field/updates': {
      id: '/field/updates'
      path: '/field/updates'
      fullPath: '/field/updates'
      preLoaderRoute: typeof FieldUpdatesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  ProfileRoute: ProfileRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminHealthRoute: AdminHealthRoute,
  AdminRulesRoute: AdminRulesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSourcesRoute: AdminSourcesRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminVesselsRoute: AdminVesselsRoute,
  AdminZonesRoute: AdminZonesRoute,
  CommandAlertsRoute: CommandAlertsRoute,
  CommandAnalyticsRoute: CommandAnalyticsRoute,
  CommandAssignmentsRoute: CommandAssignmentsRoute,
  CommandEvidenceRoute: CommandEvidenceRoute,
  CommandIncidentsRoute: CommandIncidentsRoute,
  CommandMapRoute: CommandMapRoute,
  CommandThreatsRoute: CommandThreatsRoute,
  CommandTwinRoute: CommandTwinRoute,
  CommandVesselsRoute: CommandVesselsRoute,
  FieldActiveRoute: FieldActiveRoute,
  FieldAssignmentsRoute: FieldAssignmentsRoute,
  FieldEvidenceRoute: FieldEvidenceRoute,
  FieldMissionRoute: FieldMissionRoute,
  FieldReportsRoute: FieldReportsRoute,
  FieldUpdatesRoute: FieldUpdatesRoute,
  AdminIndexRoute: AdminIndexRoute,
  CommandIndexRoute: CommandIndexRoute,
  FieldIndexRoute: FieldIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
